import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>Enlaces relacionados</Titulo>
        <div  >
          <p className="mb-4">Además de los enlaces que han ido apareciendo a lo largo de este documento, en estos enlaces encontrarás más información sobre las convalidaciones en la Formación Profesional:</p>
          <ul className="list-none ml-4" >
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">Información sobre <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="http://www.juntadeandalucia.es/educacion/portals/web/formacion-profesional-andaluza/estudiante/posibilidades-tras-formarme/convalidaciones-modulos" target="_blank" title="convalidaciones en la página web de FP Andalucía." rel="noopener"><span><strong>convalidaciones en la página web de FP Andalucía</strong></span><span>.</span></a></li>
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">Información sobre <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="https://www.todofp.es/convalidaciones-equivalencias-homologaciones/convalidaciones.html" target="_blank" title="convalidaciones en la página web del Ministerio de Educación." rel="noopener"><span><strong>convalidaciones en la página web del Ministerio de Educación</strong></span><span>.</span></a><span ></span></li>
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0"><a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="https://www.boe.es/buscar/doc.php?id=BOE-A-2020-17274" target="_blank" title="Normativa de apoyo" rel="noopener"><strong>Normativa de apoyo</strong></a> para las convalidaciones en FP.</li>
          </ul>
          <div className="flex justify-center">
            <img src="/horror.png" alt="" className=" w-[300px] h-[330px] border-2 border-black mt-4" />
          </div>
        </div>
        <Nav pos={20} />
      </div>
    </>
  );
}
