import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";
export const metadata = {
  title: "Convalidaciones en FP",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>Convalidaciones en FP</Titulo>
        <div className="flex justify-center">
          <img src="/aula.jpg" alt="" className="w-1/3 border-2 border-black mb-16" />
        </div>
        <div>
          <p className="mb-4 text-justify">
            La Subdirección General de Ordenación e Innovación de la Formación Profesional del Ministerio de Educación y Formación Profesional, informa que <strong>el plazo de presentación de solicitudes de convalidaciones de los alumnos en el centro se inicia el día que comienza el curso escolar y finaliza el último día del curso escolar.</strong> Tratándose con preferencia los expedientes presentados desde el inicio del plazo de matriculación hasta la finalización del mes de octubre.
          </p>
          <p className="mb-4 text-justify">
            Este plazo es revisado de forma estricta por el Ministerio acogiéndose al Real Decreto 1085/2020, de 9 de diciembre, por el que se establecen convalidaciones de módulos profesionales de los títulos de Formación Profesional del sistema educativo español y las medidas para su aplicación, y se modifica el Real Decreto 1147/2011, de 29 de julio, por el que se establece la ordenación general de la formación profesional del sistema educativo, regula en su Capítulo II  el Procedimiento para las convalidaciones.
          </p>
          <p className="mb-4 text-justify">
            Por todo ello, <strong>os informamos a todas aquellas personas que deseen solicitar una convalidación que sea competencia del Ministerio de Educación que envíe la documentación en el plazo más breve de tiempo posible con el fin de comprobar la ausencia de errores y así poder iniciar el trámite lo antes posible.</strong>
          </p>
          <p className="mb-4 text-justify">
            Las solicitudes de convalidaciones cuya resolución corresponden al director/a del centro docente donde esté matriculado el alumno se presentarán durante el mes de octubre.
          </p>
          <p className="mb-4 text-justify">
            <strong>Solo se podrá presentar una única solicitud de convalidación por curso académico.</strong>
          </p>
          <p className="mb-4 text-justify">
            <strong>ES MUY IMPORTANTE QUE TODA LA DOCUMENTACIÓN SEA CORRECTA Y ESTÉ COMPLETA.</strong>
          </p>
        </div>
        <Nav pos={2} />
      </div>
    </>
  );
}
