import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>Solicitud</Titulo>
        <div  >
          <div >
            <div >
              <p>Para solicitar el título <strong>deberás dirigirte al Centro docente donde finalizaste los estudios </strong>conducentes a la obtención del título solicitado. Debe ser solicitados por los alumnos, previo pago de las tasas correspondientes.</p>
              <p>Debes cumplimentar e imprimir el modelo 046 de autoliquidación de tasas de la Junta de Andalucía disponible en el siguiente enlace: <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="https://www.juntadeandalucia.es/economiayhacienda/apl/surweb/modelos/modelo046/046.jsp" target="_blank" title="Modelo 046" rel="noopener"><span>Modelo 046</span></a>. En el apartado OBLIGADO AL PAGO, se deben cumplimentar los datos personales y de domiciliación del solicitante. En el apartado DATOS GENERALES, se debe marcar la casilla AUTOLIQUIDACIÓN. En el cuadro de texto situado debajo se indica el título que se solicita. Se escribirá la fecha en la que se va a realizar y la liquidación. En el código territorial pueden utilizarse los desplegables y seleccionar en código órgano territorial CONSEJERÍA DE EDUCACIÓN Y DEPORTE, en &nbsp;&nbsp;Código provincia, la provincia donde se localice el centro y en Código centro, seleccionamos el centro donde superé el último módulo. En concepto de pago se indicará el código 0049 o bien se utilizará el desplegable y se seleccionará TASA POR EXPEDICIÓN DE TÍTULOS ACADÉMICOS Y PROFESIONALES.</p>
              <p>Se valida el documento, y nos da la opción de imprimirlo para presentarlo en la entidad bancaria y pagar o bien realizar el pago telemático. El pago telemático requiere tener certificado digital.</p>
              <p>El resto del documento será impreso mecánicamente por la entidad bancaria en el momento de realizar el ingreso si se opta por la impresión y presentación en la oficina bancaria.</p>
              <p>Una vez realizado el pago, la entidad bancaria se queda con una de las copias del modelo (el talón de cargo); le entregará al solicitante el ejemplar para el interesado y el ejemplar para la Administración. El ejemplar para la Administración se lo quedará el centro docente.&nbsp; El ejemplar para el interesado se lo devolverá el centro sellado, &nbsp;sirviéndole de resguardo de solicitud.</p>
              <p>Se remitirá al centro docente por correo postal (preferiblemente certificado con acuse de recibo) la siguiente documentación:</p>
              <ul className="list-none ml-4" >
                <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0"><strong>Fotocopia DNI </strong><strong>por ambas caras.</strong></li>
                <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0"><strong>Impreso de solicitud cumplimentado.</strong> <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" title="Impreso solicitud título [pdf - 27155 B]" href="https://www.juntadeandalucia.es/educacion/gestionafp/documentacion/Informacion_tutorial/impreso_solicitud_titulo.pdf" target="_blank" rel="noopener"> Descargar impreso de solicitud </a><span > (27155 <acronym title="Bytes" lang="en">B</acronym>)</span></li>
                <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0"><strong>Impreso 046 </strong>(se debe enviar el <strong>ejemplar para la administración </strong>y también el <strong>ejemplar para el interesado</strong>, que se devolverá sellado por el centro como resguardo del título).</li>
              </ul>
            </div>
            <div>
              <div className="rounded-2xl p-8 shadow-slate-300 shadow-[7px_7px_0px_rgb(0,0,0)] m-4 bg-blue-200">
                <div>
                  <p>Si deseas recibir la certificación académica con todas las calificaciones obtenidas en el ciclo, has de comunicarlo cuando envíes todos los documentos al centro.</p>
                  <p>Ten en cuenta que la cantidad a ingresar la indica la Ley de Presupuesto de la Comunidad Autónoma de Andalucía que esté en vigor. Pregunta a tu tutor/a el importe que has de abonar teniendo en cuenta que los decimales has de escribirlos empleando la coma.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Nav pos={22} />
      </div>
    </>
  );
}
