import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>Condiciones para convalidar las Horas de Libre Configuración</Titulo>
        <div>
          <p className="mb-4">El módulo profesional de <strong>Horas de Libre Configuración no puede ser objeto de convalidación.</strong></p>
          <p>Este módulo profesional no se evalúa de manera independiente al estar asociado a otro módulo profesional a efectos de evaluación. Cuando un alumno o alumna obtiene la convalidación de este otro módulo profesional (o lo haya superado con anterioridad), queda exento de cursar el de Horas de Libre Configuración.</p>
        </div>
        <Nav pos={10} />
      </div>
    </>
  );
}
