import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";
import Table from "@/components/table";
export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
const columns = [
  "Módulo a convalidar", "Formación a aportar"
]
const rows = [
  {
    header: "0156 Inglés", values: [
      "Lengua Extranjera LOGSE (duración de 65 horas, según el Real Decreto que establece el título de formación profesional y sus enseñanzas mínimas)\nCuando la lengua extranjera cursada y superada sea inglés.",
      "Lengua Extranjera LOGSE o de la C.A.\nCuando la lengua extranjera cursada y superada sea inglés",
      "Módulos Profesionales de Lengua\nExtranjera LOGSE de ciclos formativos de Grado Superior, en cualquiera de sus denominaciones, siempre que sea la misma que la que se desea convalidar.",
      "Certificado del Ciclo Elemental, de Inglés, de la Escuela Oficial de Idiomas.\n(RD 967/1988, de 2 de septiembre).",
      "Certificado de Nivel Intermedio (B1), de Inglés, de la Escuela Oficial de Idiomas.\n(RD 1629/2006, de 29 de diciembre).",
      "Certificado de Aptitud de Inglés de la Escuela Oficial de Idiomas.\n(RD 967/1988, de 2 de septiembre).",
      "Certificado de Nivel Avanzado (B2), o superior, de Inglés de la Escuela Oficial de Idiomas.\n(RD 1629/2006, de 29 de diciembre).",
      "Título de Grado, o equivalente, en Filología Inglesa.",
      "Título de Grado, o equivalente, en Traducción e Interpretación (Inglés).",
      "0179 Inglés."
    ]
  },
  {
    header: "0179 Inglés", values: [
      "Lengua Extranjera LOGSE (Inglés).",
      "Lengua Extranjera (duración de 90 horas, según reales decretos por los que se establecen los títulos de formación profesional y sus enseñanzas mínimas)\nCuando la lengua extranjera cursada y superada sea inglés",
      "Lengua Extranjera en Comercio Internacional.\nCuando la lengua extranjera cursada y superada sea inglés.",
      "Certificado de Aptitud de Inglés de la Escuela Oficial de Idiomas.\n(RD 967/1988, de 2 de septiembre).",
      "Certificado de Nivel Avanzado (B2), o superior, de Inglés de la Escuela Oficial de Idiomas.\n(RD 1629/2006, de 29 de diciembre).",
      "Título de Grado, o equivalente, en Filología Inglesa",
      "Título de Grado, o equivalente, en Traducción e Interpretación (Inglés)."
    ]
  }
]
export default function Home() {
  return (
    <>
      <Titulo>Condiciones para convalidar inglés</Titulo>
      <div className="m-4">
        <p>La documentación a aportar varía en función del módulo Inglés que se desee convalidar. Siempre deben ser estudios cursados y superados de lengua inglesa.</p>
        <Table columns={columns} rows={rows} />
        <div className="bg-yellow-100 rounded-2xl p-8 border-[#4e4320] border-2 text-[#4e4320] shadow-slate-500 shadow-[5px_5px_10px_rgb(0,0,0)]">
          <div className="flex items-center">
            <img src="/papel.png" alt="" />
            <h1 className="text-3xl font-bold m-4">Para saber más</h1>
          </div>
          <p>Por tanto, no es posible, <strong className="bg-yellow-400"><u>EN NINGÚN CASO</u></strong>, convalidar este módulo por haber cursado una asignatura universitaria relativa a este idioma.</p>
        </div>
      </div>
      <Nav pos={8} />
    </>
  );
}
