import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";
import Link from "next/link";
export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>¿Qué estudios puedo alegar?</Titulo>
        <div className="m-4">
          <ul className="list-none">
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">
              Para solicitar la convalidación de módulos profesionales de un ciclo formativo de FP <strong>se pueden alegar enseñanzas </strong>cursadas dentro <strong>del Sistema Educativo </strong>y Unidades de Competencia acreditadas. Por tanto, se puede aportar:
              <ul className="list-none ml-4">
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Otros ciclos formativos</strong> de Formación Profesional de grado medio o superior cursados con anterioridad.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Enseñanzas universitarias</strong>: diplomaturas, licenciaturas, grados.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  Las <strong>antiguas enseñanzas de Formación Profesional</strong> de primer y segundo grado (títulos de Técnico auxiliar y Técnico especialista).
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  Ciclos formativos de <strong>Enseñanzas deportivas</strong> o de <strong>Artes Plásticas y Diseño</strong>.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  Certificaciones académicas Oficiales de idioma (del mismo idioma que se solicita la convalidación y de nivel idóneo).
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  Unidades de Competencia acreditadas.
                </li>
              </ul>
            </li>
          </ul>

          <ul className="list-none">
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">
              Las enseñanzas siguientes no se pueden alegar:
              <ul className="list-none ml-4">
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Carnés profesionales y cursos de Formación Profesional para el empleo (FPO y FP continua)</strong>, distintos de los que conducen a la obtención de un <em>Certificado de profesionalidad</em> y a la acreditación oficial de unidades de competencia.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Cursos privados</strong> realizados en academias y centros de formación que no imparten enseñanzas oficiales.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Cursos propios impartidos en la Universidad</strong>, que no sean másteres oficiales como los cursos de experto, cursos de especialización, ...
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Títulos propios no oficiales de universidad</strong>.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Certificados de idiomas no oficialmente aceptados</strong>.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Experiencia laboral</strong>.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Formación no formal</strong>.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Titulaciones extranjeras homologadas</strong>.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Títulos equivalentes LOGSE</strong>.
                </li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0">
                  <strong>Formaciones de otros ministerios que tienen concedida por normativa la equivalencia general o específica</strong>.
                </li>
              </ul>
            </li>
          </ul>

          <ul className="list-none space-y-2">
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">
              Los <strong>módulos profesionales</strong> que <strong>hayan sido previamente </strong><strong>convalidados no podrán ser alegados para convalidar.</strong> Solo se puede alegar materias que hayan sido cursadas y superadas. Los títulos extranjeros homologados tampoco podrán ser causa de una nueva convalidación con otros módulos profesionales.
            </li>
          </ul>

          <ul className="list-none space-y-2">
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">
              Los <strong>estudios que tengan concedida la equivalencia específica o genérica </strong><Link className="text-blue-500 border-b-2 border-blue-500 hover:border-b-0" href="https://www.juntadeandalucia.es/educacion/portals/web/formacion-profesional-andaluza/quiero-formarme/posibilidades-tras-formarme/equivalencias/tabla-equivalencias"><strong>(aquí los tenéis)</strong></Link>, a efectos académicos y/o profesionales, con títulos de Formación Profesional <strong>no podrán ser utilizados a su vez para la convalidación de sus módulos profesionales</strong>; por tanto, quien haya superado la totalidad de un ciclo formativo LOGSE no podrá aportarlo para solicitar la convalidación de ningún módulo profesional del título LOE equivalente que lo sustituye. Las convalidaciones que aparecen recogidas en el anexo IV del Real Decreto que regula cada título están reservadas para quien no ha podido finalizar el ciclo formativo que se extingue y debe transitar al nuevo ciclo formativo equivalente, o para quien solicita dichas convalidaciones para un título diferente de aquel con el que se ha declarado la equivalencia.
            </li>
          </ul>

          <ul className="list-none space-y-2">
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">
              Haber cursado enseñanzas superiores no siempre da derecho a la convalidación de enseñanzas relacionadas, pero de menor nivel, aunque en ambas haya materias con nombres similares.
            </li>
          </ul>
          <p></p>
        </div>
        <div className="flex justify-center">
          <img src="/aula_ordenadores.jpg" alt="" className="w-[350px] h-[350px] border-2 border-black"/>
        </div>

        <Nav pos={4} />
      </div>
    </>
  );
}
