import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>¿Dónde encontrar que modulos son convalidables?</Titulo>
        <div>
          <p>Son dos los documentos que debes consultar:</p>
          <ul className="list-none ml-4">
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">Por un lado, los diferentes <strong>Anexos del </strong><a className="text-blue-500 border-b-2 border-blue-500 hover:border-b-0" href="https://www.boe.es/buscar/doc.php?id=BOE-A-2020-17274" target="_blank" title="Real Decreto&nbsp;1085/2020, de 9 de diciembre" rel="noopener"><strong>Real Decreto&nbsp;</strong><em>1085/2020, de 9 de diciembre, por el que se establecen convalidaciones de módulos profesionales de los títulos de Formación Profesional del sistema educativo español y las medidas para su aplicación, y se modifica el Real Decreto 1147/2011, de 29 de julio, por el que se establece la ordenación general de la formación profesional del sistema educativo.</em></a> Aquí puedes consultar las tablas de convalidaciones del Real decreto 1085/2020, de 9 de diciembre (<a className="text-blue-500 border-b-2 border-blue-500 hover:border-b-0" href="https://www.todofp.es/convalidaciones-equivalencias-homologaciones/convalidaciones/normativa-de-apoyo.html" target="_blank" title="tablas de convalidación" rel="noopener"><span>tablas de convalidación</span></a><span>).</span><span></span></li>
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">Por otro, el <strong>Anexo IV del Real Decreto </strong>que crea el título LOE que estás estudiando, ya que establece las convalidaciones con módulos LOGSE del mismo Ciclo. Quien haya superado la totalidad de un ciclo formativo LOGSE no podrá aportarlo para solicitar la convalidación de ningún módulo profesional del ciclo formativo LOE que lo sustituye. Estas convalidaciones están reservadas para quien transita a un ciclo formativo LOE desde un ciclo formativo LOGSE, sin haberlo finalizado ni obtenido el título.</li>
          </ul>
          <p>Ten en cuenta que los<strong> módulos profesionales con el mismo código y denominación</strong> presentes en diferentes ciclos formativos LOE<strong> son en realidad el mismo módulo profesional. </strong>Estos módulos se denominan<strong> transversales. </strong>Si superas un módulo profesional transversal en un ciclo formativo, lo tendrás superado en cualquier otro del que también forme parte y <strong>la calificación obtenida se traslada de un ciclo al otro sin necesidad de convalidación ni más trámite</strong>.<span></span></p>
          <p>Los módulos profesionales de FOL y EIE tienen en todos los ciclos formativos LOE la misma denominación, pero diferentes códigos. Por tanto, no hay arrastre de calificación sino convalidación. Se deben cursar o convalidar de un ciclo formativo a otro (siempre que se cumplan los requerimientos para ello).</p>
          <ul className="list-none ml-4">
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">La convalidación del módulo FOL puedes consultarla en el siguiente enlace: <a className="text-blue-500 border-b-2 border-blue-500 hover:border-b-0" href="https://www.todofp.es/convalidaciones-equivalencias-homologaciones/convalidaciones.html" target="_blank" title="Convalidación de FOL" rel="noopener"><span>Convalidación de FOL</span></a>.</li>
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">La convalidación del módulo EIE puedes consultarla en el siguiente enlace: <a className="text-blue-500 border-b-2 border-blue-500 hover:border-b-0" href="https://www.todofp.es/convalidaciones-equivalencias-homologaciones/convalidaciones.html" target="_blank" title="Convalidación de EIE" rel="noopener"><span>Convalidación de EIE</span></a>.</li>
          </ul>
        </div>
        <div className="flex justify-center">
          <img src="/pato.jpg" alt="" className="border-2 border-black w-[300px] h-[300px] m-8"/>
        </div>
        <Nav pos={5} />
      </div>
    </>
  );
}
