import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
    <div className="m-4">
      <Titulo>Condiciones para convalidar el módulo de Proyecto</Titulo>
      <div>
        <p>El módulo profesional de Proyecto correspondiente a títulos de Formación profesional de grado superior no podrá ser objeto de convalidación ni de exención en ningún caso.</p>
      </div>
      <Nav pos={11} />
    </div>
    </>
  );
}
