import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4 mr-8">
        <Titulo>Solicitud del título</Titulo>
        <div className="rounded-2xl p-8 shadow-slate-300 shadow-[7px_7px_0px_rgb(0,0,0)] m-4 bg-blue-200">
          <p>Aquí encontrarás los pasos a seguir para solicitar el título del ciclo una vez hayas superado todos los módulos formativos que lo conforman.</p>
          <div className="flex justify-center">
            <img src="/mondongo.png" alt="" className="w-[300px]" />
          </div>
        </div>
        <Nav pos={21} />
      </div>
    </>
  );
}
