import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>¿Puedo convalidar un módulo acreditando experiencia laboral?</Titulo>
        <div className="flex justify-between">
          <div className="w-[70%] text-justify">
            <p className="mb-2"><strong>Salvo el módulo de Formación en Centros de Trabajo </strong><em>(las "prácticas")</em>, <strong>la respuesta es no</strong>. En general, <strong>no es posible convalidar un módulo acreditando experiencia laboral a través de un informe de vida laboral.</strong></p>
            <p className="mb-2">Si alguna persona cree que con su experiencia profesional ha adquirido las competencias necesarias de un módulo concreto, debe acreditar la posesión de esas unidades de competencia bien mediante un <strong>certificado de profesionalidad</strong> o bien porque ha participado en un <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="http://todofp.es/acreditacion-de-competencias.html" target="_blank" title="procedimiento de acreditación de competencias profesionales" rel="noopener"><strong>procedimiento de acreditación de competencias profesionales</strong></a> y así se lo han reconocido, <u>no a través de un certificado de vida laboral</u>. <strong>Tampoco serán válidos los resguardos de haber solicitado el certificado de profesionalidad, los diplomas o certificados de asistencia expedidos por el centro o entidad de formación u otros documentos justificativos distintos de los indicados. </strong>Estas convalidaciones se regulan en el anexo V.A del Real Decreto que crea el título que se está estudiando (en este anexo se indican las unidades de competencia que se adquieren al superar cada módulo profesional).</p>
            <p className="mb-2">Por tanto,<strong> las unidades de competencia debidamente acreditadas pueden ser aportadas para solicitar la convalidación de módulos profesionales según lo regulado en el anexo V.A del Real Decreto </strong>que regula cada título siempre que se aporte el <strong>certificado de profesionalidad </strong>o la <strong>certificación </strong><strong>oficial de la acreditación de la Unidad de Competencia.</strong><span></span></p>
          </div>
          <div>
            <img src="/chamba.jpg" alt="" className="w-[320px] h-[350px] border-2 border-black m-4 ml-0" />
          </div>
        </div>
        <Nav pos={13} />
      </div>
    </>
  );
}
