import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";
import Table from "@/components/table";
export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
const columns = [
  "Módulo a convalidar",
  "Formación a aportar"
]
const rows = [
  {header: "2ª Lengua Extranjera LOGSE", values: [
    "MP Segunda Lengua Extranjera LOGSE, siempre que sea la misma que la que se desea convalidar.",
    "Certificado de Nivel Intermedio (B1), equivalente o superior, de la Escuela Oficial de Idiomas (RD 1629/2006, de 29 de diciembre) siempre que sea de la misma lengua extranjera que la que se desea convalidar.",
    "Título de Grado en Filología o equivalente, de la misma especialidad que la lengua extranjera que se desea convalidar.",
    "Título de Grado Traducción e Interpretación, o equivalente, de la misma especialidad que la lengua extranjera que se desea convalidar."
  ]},
  {header: "0180 2ª Lengua Extranjera.", values:[
    "Segunda Lengua Extranjera LOGSE.\nCuando la lengua extranjera cursada y superada sea la misma que se desea convalidar.",
    "Certificado del Ciclo Elemental o de Aptitud, de la Escuela Oficial de Idiomas.\n(RD 967/1988, de 2 de septiembre).\n(De la misma lengua extranjera que se desea convalidar).",
    "Certificado de Nivel Intermedio (B1), o superior, de la Escuela Oficial de Idiomas. (RD 1629/2006, de 29 de diciembre).\n(De la misma lengua extranjera que se desea convalidar).",
    "Título de Grado, o equivalente, en Filología o en Traducción e Interpretación.\n(De la misma especialidad que la lengua extranjera que se desea convalidar)."
  ]}
]
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>Condiciones para convalidar segunda lengua extranjera</Titulo>
        <div>
          <p>Para poder convalidar el módulo de Segunda Lengua Extranjera debe aportarse siempre estudios cursados y superados en la misma lengua que se desee convalidar. Es necesario acreditar alguna de las siguientes condiciones:</p>
        </div>
        <Table columns={columns} rows={rows} />
        <div className="bg-yellow-100 rounded-2xl p-8 border-[#4e4320] border-2 text-[#4e4320] shadow-slate-500 shadow-[5px_5px_10px_rgb(0,0,0)]">
          <div className="flex items-center">
            <img src="/papel.png" alt="" />
            <h1 className="text-3xl font-bold m-4">Para saber más</h1>
          </div>
          <p>Por tanto, no es posible, <strong className="bg-yellow-400"><u>EN NINGÚN CASO</u></strong>, convalidar este módulo por haber cursado una asignatura universitaria relativa a este idioma.</p>
        </div>
      </div>
      <Nav pos={9} />
    </>
  );
}
