import Image from "next/image";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div>
      Pagina Principal
    </div>
  );
}
