import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";
import Tabla from "@/components/table";
const columns = [
  "Módulo a convalidar",
  "Formación a aportar"
]
const rows = [
  { header: "FOL GM (LOGSE Ley Orgánica 1/1990, de 3 de octubre)", values: ["FOL GM LOGSE", "FOL GS LOGSE", "FOL GM LOE", "FOL GS LOE"] },
  { header: "FOL GS (LOGSE Ley Orgánica 1/1990, de 3 de octubre)", values: ["FOL GS LOGSE"]},
  { header: "FOL GM (LOE Ley Orgánica 2/2006, de 3 de mayo)", values: [
    "FOL GM LOE",
    "FOL GS LOE", "FOL GM LOGSE + Certificado nivel básico actividad preventiva",
    "FOL GS LOGSE + Certificado nivel básico actividad preventiva",
    "Título Técnico Superior en Prevención de Riesgos Profesionales"
  ]},
  { header: "FOL GS (LOE Ley Orgánica 2/2006, de 3 de mayo)", values: [
    "FOL GM LOE", 
    "FOL GS LOE",
    "FOL GM LOGSE + Certificado nivel básico actividad preventiva",
    "FOL GS LOGSE + Certificado nivel básico actividad preventiva",
    "Título Técnico Superior en Prevención de Riesgos Profesionales"
  ]}
]
export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>Condiciones para convalidar FOL</Titulo>
        <div>
          <div className="text-justify">
            <p>Para poder convalidar el módulo de FOL (Formación y Orientación Laboral) es necesario acreditar alguna de las siguientes condiciones:</p>
            <ul className="list-none ml-4">
              <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">Si el módulo a convalidar pertenece a un ciclo LOE (Ley Orgánica 2/2006, de 3 de mayo). <strong>Para esta convalidación es indiferente que los módulos que se aporten sean de grado medio o superior.</strong>
                <ul className="list-none ml-4">
                  <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>Tener aprobado el módulo de FOL en cualquier otro Ciclo LOE y acreditarlo documentalmente. </strong></li>
                  <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>Tener aprobado el módulo de FOL en un Ciclo LOGSE (Ley Orgánica 1/1990, de 3 de octubre) y poseer un certificado que acredite que se posee la formación establecida para el desempeño de las funciones de nivel básico de la actividad preventiva </strong>(PRL). Sirve cualquier curso de PRL impartido por alguna entidad legalmente constituida, de una duración no inferior a 30 horas y cuyos contenidos incluyan los que indica el anexo IV del Real Decreto 39/1997, de 17 de enero (BOE de 31 de enero de 1997), por el que se aprueba el Reglamento de los Servicios de Prevención. <strong>El certificado del curso de PRL deberá hacer constar específicamente tanto la duración como los contenidos impartidos.</strong></li>
                  <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>Poseer el título de Técnico Superior en Prevención de Riesgos Profesionales derivado de la Ley Orgánica 1/1990, de 3 de octubre.</strong></li>
                </ul>
              </li>
            </ul>
            <ul className="list-none ml-4">
              <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">Si el módulo a convalidar pertenece a un ciclo LOGSE de grado medio (Ley Orgánica 1/1990, de 3 de octubre):
                <ul className="list-none ml-4">
                  <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>Tener aprobado el módulo de FOL en un Ciclo LOGSE (Ley Orgánica 1/1990, de 3 de octubre). </strong></li>
                  <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>Tener aprobado el módulo de FOL en cualquier otro Ciclo LOE y acreditarlo documentalmente.</strong></li>
                </ul>
              </li>
            </ul>
            <ul className="list-none ml-4">
              <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">Si el módulo a convalidar pertenece a un ciclo LOGSE de grado superior (Ley Orgánica 1/1990, de 3 de octubre):&nbsp;
                <ul className="list-none ml-4">
                  <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>Tener aprobado el módulo de FOL en un Ciclo LOGSE de Grado Superior (Ley Orgánica 1/1990, de 3 de octubre).</strong></li>
                </ul>
              </li>
            </ul>
            <p><strong></strong></p>

          </div>
        </div>
        <Tabla columns={columns} rows={rows} />
        <Nav pos={6} />
      </div>
    </>
  );
}
