import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>¿Qué documentación debo enviar al centro?</Titulo>
        <div  className="text-justify">
          <p>Debes presentar la solicitud de convalidación de módulos profesionales, acompañada de la documentación establecida correspondiente, en el centro.&nbsp;<strong>En ningún caso puedes enviar por tu cuenta la solicitud al Ministerio.</strong></p>
          <ul className="list-none ml-4" >
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0"><strong>Solicitud de convalidación </strong>que encuentras en este <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="https://www.juntadeandalucia.es/educacion/portals/web/formacion-profesional-andaluza/estudiante/posibilidades-tras-formarme/convalidaciones-modulos" target="_blank" title="Convalidaciones entre módulos profesionales" rel="noopener"><strong>enlace (ver &quot;Impreso solicitud convalidación módulos profesionales&quot;)</strong></a>. En ese documento es imprescindible que cumplimentes todos los apartados. En este <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="https://www.juntadeandalucia.es/educacion/secretariavirtual/consulta/oferta-educativa-formacion-profesional-parcial/" target="_blank" title="Oferta de centros docentes sostenidos con fondos públicos para el procedimiento de admisión en oferta parcial diferenciada (modalidades presencial, semipresencial y distancia) para el curso escolar" rel="noopener"><strong>enlace</strong></a> puedes consultar los módulos de cada ciclo impartido con <strong>su nombre y el código exacto. Para ello, debes desplegar dentro de cada centro, el apartado &quot;Módulos ofertados de este ciclo&quot;</strong>. <strong>Recuerda que el plazo para enviar la solicitud de convalidación concluye </strong><strong>a finales de octubre</strong>.</li>
          </ul>
          <ul className="list-none ml-4" >
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0"><strong>Fotocopia del Documento Nacional de Identidad </strong>(DNI) o fotocopia del Pasaporte o de la Tarjeta de Extranjero/a o del Permiso de Residencia (temporal o definitivo) o del Visado de Estudios.</li>
          </ul>
          <ul className="list-none ml-4" >
            <li className="relative pl-6 before:content-['✓'] before:text-emerald-300 before:absolute before:left-0">Además, debe incluirse la siguiente documentación, <strong>ya sea original o fotocopia compulsada</strong> (recuerda que puedes compulsar un documento en cualquier Administración Pública que cuente con registro simplemente presentando la copia y enseñando el original):
              <ul className="list-none ml-4" >
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>Certificación académica oficial expedida por el centro docente donde has cursado los estudios que alegas</strong>. En el caso de estudios universitarios, es obligatorio presentar original o fotocopia compulsada de la certificación académica oficial, con indicación de las horas o créditos de cada materia superada.</li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>En el caso de alegar un título que acredite la formación previa alegada, debes presentar el título oficial o resguardo de haberlo solicitado</strong>. En el caso de que desees convalidar alegando haber cursado otro ciclo formativo, es suficiente con el certificado académico de notas y no es necesario que adjuntes también la copia del título o el resguardo de haberlo solicitado.</li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>En el caso de alegar enseñanzas universitarias, además de la certificación académica oficial con indicación de las horas o créditos de cada materia superada, deberás presentar <u>los programas de las asignaturas que haya cursado sellados </u></strong><u>(el sello debe ser original y no vale una fotocopia del programa en el que el sello no sea original) por el centro universitario</u>. Estos programas deben recoger la <strong>duración y contenidos teóricos y prácticos estudiados</strong>.</li>
                <li className="relative pl-6 before:content-['⇒'] before:text-emerald-300 before:absolute before:left-0"><strong>En el caso de alegar unidades de competencia oficialmente acreditadas, certificación oficial de la acreditación de la Unidad de Competencia o Certificado de profesionalidad expedido por la Administración Laboral competente, obtenido de acuerdo con lo establecido en el RD 34/2008, de 18 de enero</strong>.</li>
              </ul>
            </li>
          </ul>
          <p><strong>Aunque ya se ha dicho anteriormente, se recuerda que&nbsp;<u>todos los documentos (excepto el DNI y el documento de la solicitud de convalidación) tienen que ser original o copia compulsada</u>.&nbsp;<u>También se recuerda que el centro no puede tramitar ante el Ministerio de Educación ninguna solicitud que no venga acompañada de la documentación establecida.</u></strong></p>
          <p><strong><u>El solicitante deberá estar matriculado en los módulos profesionales que solicita convalidar y haber satisfecho los derechos de matrícula en las enseñanzas para las cuales solicita la convalidación.</u></strong></p>
          <p><strong>Las convalidaciones entre estudios universitarios y de Formación Profesional se podrán solicitar cuando estos últimos pertenezcan al espacio de la educación superior</strong>. Además, el número de módulos profesionales de los ciclos de grado superior convalidados <strong>no podrá superar el 60% de la totalidad de créditos ECTS</strong> establecidos en el real decreto por el que se establece el título Técnico Superior y se fijan los aspectos básicos del currículo, siempre que se aporten <strong>enseñanzas universitarias que estén relacionadas con el campo de conocimiento y exista similitud entre las competencias, conocimientos y resultados de aprendizaje.</strong></p>
          <div className="flex justify-center">
            <img src="/carpeta.png" alt="" className="w-[300px] h-[350px] border-black border-2 m-12" />
          </div>
        </div>
        <Nav pos={15} />
      </div>
    </>
  );
}
