import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";
export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
      <Titulo>Cómo saber si me convalidaran un módulo si he alegado estudios universitarios</Titulo>
        <div>
          <p>No se puede saber a priori.</p>
          <p>Por eso el Ministerio de Educación y Formación Profesional solicita los programas universitarios sellados: para poder analizar caso a caso y de forma individualizada cada convalidación.</p>
          <p>El Ministerio de Educación y Formación Profesional tiene en su página Web información sobre la convalidación de módulos profesionales aportando estudios universitarios. La podéis encontrar en este <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="https://www.todofp.es/convalidaciones-equivalencias-homologaciones/convalidaciones.html" target="_blank" title="Convalidaciones en Formación Profesional" rel="noopener"><strong>enlace</strong></a>.</p>
        </div>
      <Nav pos={17} />
      </div>
    </>
  );
}
