import Image from "next/image";
import Titulo from "@/components/titulo";
import Nav from "@/components/nav";

export const metadata = {
  title: "Información general: convalidaciones, exenciones y títulos",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div className="m-4">
        <Titulo>Tramitación y recogida</Titulo>
        <div className="flex justify-center">
          <p className="text-justify">Cuando el centro en el que pides el título reciba la documentación, te devolverá el resguardo indicando que el título se encuentra en trámite. Resguardo que deberás guardar junto con el ejemplar para el interesado del impreso 046 hasta la llegada del título. Este puede tardar varios años en llegar al centro, será entonces cuando se te comunicará por correo que ya puedes recogerlo (también podrás recibirlo a través de las Delegaciones Territoriales).</p>
          <div className="m-4">
            <img src="/luz.png" alt="" className="w-[500px]" />
          </div>
        </div>
        <div className="rounded-2xl p-8 shadow-slate-300 shadow-[7px_7px_0px_rgb(0,0,0)] m-4 bg-blue-200" >
            <div >
            <div >
              <div  >
                <p >Puedes encontrar más información al respecto:</p>
                <ul className="list-none ml-4" >
                  <li className="relative pl-6 before:content-['✓'] before:text-emerald-400 before:absolute before:left-0">En el artículo 7 de la&nbsp;<a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="http://www.juntadeandalucia.es/boja/1996/67/50" target="_blank" title="ORDEN de 21 de mayo de 1996, por la que se regulan el procedimiento de expedición y la organización y funcionamiento del Registro de los títulos académicos y profesionales correspondientes a las enseñanzas establecidas por la Ley Orgánica 1/1990, de 3 de octubre, de Ordenación General del Sistema Educativo" rel="noopener">ORDEN de 21 de mayo de 1996, por la que se regulan el procedimiento de expedición y la organización y funcionamiento del Registro de los títulos académicos y profesionales correspondientes a las enseñanzas establecidas por la Ley Orgánica 1/1990, de 3 de octubre, de Ordenación General del Sistema Educativo</a> y</li>
                </ul>
                <ul className="list-none ml-4" >
                  <li className="relative pl-6 before:content-['✓'] before:text-emerald-400 before:absolute before:left-0" >En el <a className="underline text-blue-500 hover:text-blue-700 hover:no-underline" href="https://www.boe.es/buscar/doc.php?id=BOE-A-2020-342" target="_blank" title="Real Decreto 700/2019, de 29 de noviembre, por el que se modifica el Real Decreto 1850/2009, de 4 de diciembre, sobre expedición de títulos académicos y profesionales correspondientes a las enseñanzas establecidas por la Ley Orgánica 2/2006, de 3 de mayo, de Educación, para fijar el formato, el contenido y el soporte documental del Suplemento Europeo al Título de las Enseñanzas Artísticas." rel="noopener">Real Decreto 700/2019, de 29 de noviembre, por el que se modifica el Real Decreto 1850/2009, de 4 de diciembre, sobre expedición de títulos académicos y profesionales correspondientes a las enseñanzas establecidas por la Ley Orgánica 2/2006, de 3 de mayo, de Educación, para fijar el formato, el contenido y el soporte documental del Suplemento Europeo al Título de las Enseñanzas Artísticas.</a></li>
                </ul>
                <p ></p>
              </div>
            </div>
          </div>
        </div>
        <Nav pos={23} />
      </div>
    </>
  );
}
